# Generated by Django 4.2.20 on 2025-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profil_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
